#%RAML 1.0 DataType
type: object
properties:
  org-id:
    required: false
    type: string
  org-name:
    required: false
    type: string
  dept-id:
    required: false
    type: string
  dept-name:
    required: false
    type: string