#%RAML 1.0 Trait
description: it will force the client ot pass client id and client secret
headers:
  client_id:
    required: true
    type: string
  client_secret:
    required: true
    type: string