#%RAML 1.0 Library
usage: for add all the data types and the body
types:
  #datatype
  error-datatype: !include datatypes/error-datatype.raml
  msg-datatype: !include datatypes/msg-body-datatype.raml
  success-datatype: !include datatypes/success-datatype.raml
  update-datatype: !include datatypes/update-datatype.raml
 